### ISSUE TITLE
写的不错！代码量少，还不丢材质好用！

### ISSUE THREAD

**Issue by weiyu666** [triroakenshield/RevitExportTest#1]
![image](https://user-images.githubusercontent.com/22174508/87893832-9c446800-ca73-11ea-864b-9a6aa9c464ee.png)
自己生成了两个文件一个glb还有一个是bin~  json是有格式化的
![image](https://user-images.githubusercontent.com/22174508/87893878-c138db00-ca73-11ea-9b2c-566dbd5fb0d7.png)

**Comment by triroakenshield** [comment]
Спасибо, glb-файл эквивалентен паре json/bin - один из вариантов можно закоментировать в коде ;=)
