### ISSUE TITLE
导出的模型只能是Revit的“着色”或者一致颜色吗？

### ISSUE THREAD

**Issue by weiyu666** [triroakenshield/RevitExportTest#3]
如下图revit下的：
![image](https://user-images.githubusercontent.com/22174508/87894182-9602bb80-ca74-11ea-9759-43f4de026c65.png)
用微软的3D查看器打开的就只能是Revit的“着色”模式不能是真实模式吗？
![image](https://user-images.githubusercontent.com/22174508/87894230-c0547900-ca74-11ea-917c-e547cdac44e6.png)

**Comment by weiyu666** [comment]
原始的数据：
[昆山市金华村农房设计.zip](https://github.com/triroakenshield/RevitExportTest/files/4945261/default.zip)

**Comment by triroakenshield** [comment]
Тут есть много аспектов, мой код передаёт только цвет и прозрачность.
Визуальный стиль во многом определяется программой просмотра, по этому [в статье на habr'е](https://habr.com/ru/post/472264/) я использовал A-Frame - там есть возможность это настраивать

**Comment by weiyu666** [comment]
I know you just passed the color value RGBAlpha and no texture map, but I seem to see other people have a way to use the Windows registry to get the material library, then export the texture and link it.
