### ISSUE TITLE
Сборка проекта, проблемы с ссылками на библиотеки

### ISSUE THREAD

**Issue by GeorgGrebenyuk** [triroakenshield/RevitExportTest#4]
Добрый день, интересно попробовать ваше приложение, с программированием только недавно начал знакомиться и немного на "вы";
У вас в сборке есть необходимости обновить ссылки на как миниумум 4 ресурса, Revit API - это понятно, что для весрии 2021; NewtonSoft.Json - это пакет NuGet, а вот SharpGLTF и SharpGLTF.Toolkit - это откуда ставятся и dll ли это? Во всяком случае сборка SharpGLTF с гитхаба не содержит этих элементов, также как и NuGet-пакеты для них. Подскажите пожалуйста - какие это сборки надо доустановить?
И еще 1 вопрос - почему вы сделали фиксированной версию NewtonSoft.Json в отличие от тега "Конкретная версия - false" в остальных библиотеках?
P.S. Я доустановил так:
- SharpGLTF\src\SharpGLTF.Toolkit\bin\Debug\netstandard2.0\SharpGLTF.Toolkit.dll
- SharpGLTF\src\SharpGLTF.Toolkit\bin\Debug\netstandard2.0\SharpGLTF.Core.dll
using SharpGLTF; - как я понимаю вообще не нужно?
- добавил в C:\ProgramData\Autodesk\Revit\Addins\2021 файл RevitExportTest.addin (приписал в нем путь к dll скомипилированному) а в Ревите вызывается такая ошибка при запуске 
![image](https://user-images.githubusercontent.com/55656376/95905903-17cb6200-0da2-11eb-86c1-78fb7011d072.png)
P.S.S. И еще я менял Net Framework с 4.7.2 на 4.8 .. или вы на версии 2020 испытывали?

**Comment by triroakenshield** [comment]
Я давно ждал этого вопроса, но видимо все остальные справились без меня ;=)
На сайте khronos есть табличка с длиным списком разных либ для работы с glTF, там я и нашёл SharpGLTF - https://github.com/VPenades/SharpGLTF
Там проблема в том, что в TargetFrameworks нет Net Framework, что бы это побороть
1. Скачиваем репозиторий
2. В файлы csproj ручками добовляем TargetFrameworks
3. Собираем
4. Ручками подключаем готовые библиотеки к нашему проект

в SharpGLTF ссылка на NewtonSoft.Json

**Comment by triroakenshield** [comment]
[упс](https://github.com/vpenades/SharpGLTF/commit/b8c755435fff807ff8628076d99d498caae19483)

**Comment by triroakenshield** [comment]
попробывал собрать для Net Framework 4.8
[net48.zip](https://github.com/triroakenshield/RevitExportTest/files/5386116/net48.zip)
кажется NewtonSoft.Json уже не нужен

**Comment by GeorgGrebenyuk** [comment]
Добрый вечер!
Добрался вот только до этого, уточню еще раз - под фразой "_В файлы csproj ручками добовляем TargetFrameworks_" вы имеете в виду для репозитория с SharpGLTF менять конфигурации файлов CSPROJ от Core & Toolkits до таких значений?
![image](https://user-images.githubusercontent.com/55656376/96344950-01275280-10a3-11eb-9181-7a131e1953f2.png)
Тогда при пересборке этих решений, они не формируются для указываемых версий - возможно, я делаю что-то не так?

**Comment by triroakenshield** [comment]
нужно добавить ссылки на либы для новой платформы
у тебя же в ошибке прямым текстом написано - нету System.Runtime.CompilerServices.Unsafe.dll
попробуй либы которые я выложил в архиве, и посмотри - что там прицепилось
